name: Upload Worker to CloudFlare

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Upload
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Upload Cloudflare Workers
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: versions upload
          secrets: |
            DESTINATION_EMAIL
            DIRECT_EMAIL_USERS
        env:
          DESTINATION_EMAIL: ${{ secrets.DESTINATION_EMAIL }}
          DIRECT_EMAIL_USERS: ${{ secrets.DIRECT_EMAIL_USERS }}
